### ISSUE TITLE
怎么在linux下跑谱？

### ISSUE THREAD

**Issue by avlgood** [NeymarL/ChineseChess-AlphaZero#11]
我下载了代码到linux虚拟机，然后跑谱遇到错误，怎么处理？

$ python ChineseChess-AlphaZero/colaboratory/run.py
  File "ChineseChess-AlphaZero/colaboratory/run.py", line 28
    config.internet.upload_url = f'{config.internet.base_url}/api/upload_game_file/128x7'
                                                                                        ^
SyntaxError: invalid syntax

**Comment by NeymarL** [comment]
Python版本需要3.6+

**Comment by emc2314** [comment]
虚拟机没有cuda吧...没法跑

**Comment by NeymarL** [comment]
虚拟机也可以安装CUDA
