### ISSUE TITLE
无法下棋

### ISSUE THREAD

**Issue by leven99** [NeymarL/ChineseChess-AlphaZero#12]
据[针对非开发人员的下棋教程中的下棋](https://github.com/NeymarL/ChineseChess-AlphaZero/wiki/For-Non-Developers#%E4%B8%8B%E6%A3%8B)，下载[自制界面CPU版本](https://pan.baidu.com/s/1-8F0GZpqILxQx9t9P7PFiA)(run_self_play-cpu.zip, 56.2 MB)，文件中没有```play_game```文件夹，也没有```play_games.exe```执行文件，尝试执行文件中唯一的可执行文件```run_self_play.exe```，界面卡在如下：
![image](https://user-images.githubusercontent.com/22231104/40883340-a5561d82-672c-11e8-88b5-26afa55a72aa.png)

**Comment by wjpws** [comment]
你下载的是selfplay客户端 不是GUI。至于为什么CPU的selfplay运行不了 是因为CPU版本太慢 作者已经暂时停止更新CPU版本了 而服务器目前不接受来自2.0的棋谱

**Comment by NeymarL** [comment]
自制界面的链接放错了不好意思，现已更正。
