### ISSUE TITLE
关于ChineseChess-AlphaZero的建议

### ISSUE THREAD

**Issue by leven99** [NeymarL/ChineseChess-AlphaZero#13]
* 建议将引擎与GUI分离为两个项目，单独设计开发，就像Leela Zero与Sabaki

**中国象棋规则与协议**
* [中国象棋通用引擎协议，V3.0](http://www.xqbase.com/protocol/cchess_ucci.htm)

**Comment by NeymarL** [comment]
Sabaki只是围棋的一个界面的吧，跟Leela Zero貌似没什么关系，实现GTP协议也是在LZ的项目里，并没有单开一个项目。CCZero也支持UCI协议，可以用冰河五四等界面加载。

**Comment by leven99** [comment]
Sabaki可以加载LeelaZero是因为它们都实现了GTP协议。

自制界面play_games(GUI)程序与CCZero(UCI引擎)是在同一个项目中吗？我没有找到play_games(GUI)项目的介绍，如果是在一个项目中，可以将两个分离为单独的项目，因为只要都实现了UCI协议，就可以各自发展，同时可以精简CCZero的代码库。

至于冰河五四的界面，说实话它有些过时了，也不支持跨平台。

**Comment by wjpws** [comment]
感觉并没有这样做的必要。你也知道作者基本是单干的 分离对这个计划几乎没有任何帮助

**Comment by NeymarL** [comment]
自制界面与UCI引擎是在一个项目里，但是没有必要把界面单独移出去，因为这个界面只是为了此项目而实现的，并没有支持任何协议。

**Comment by leven99** [comment]
项目有支持 [UCCI](http://www.xqbase.com/protocol/cchess_ucci.htm) 协议的打算吗?

**Comment by NeymarL** [comment]
没有支持UCCI协议的打算
