### ISSUE TITLE
能否将selfplay的默认线程从20改为2？

### ISSUE THREAD

**Issue by wjpws** [NeymarL/ChineseChess-AlphaZero#14]
过多的线程并行计算会影响MCTS的质量 在LZ中他们曾经采用的是1线程和2线程 如果这个对速度损失不太大的话 我觉得有必要做这个修改来提高训练的MCTS质量 同时希望UCI引擎也引入T参数设置 而不是卡死在20

**Comment by NeymarL** [comment]
2和20速度相差很多，UCI引擎修改线程数以后可以加入

**Comment by wjpws** [comment]
应该可以用多开方式解决速度问题吧？不清楚现在比如输入进程数为4的话 是每个进程分配总核心/4的线程数 还是都分配最大线程数?

**Comment by NeymarL** [comment]
Python里的线程和操作系统的线程并不一样，Python的多线程是并发的，不是并行的，一个进程里想分配多少线程都可以。

**Comment by wjpws** [comment]
能否有折中的方案在尽可能提高MCTS质量的情况下不损失太多速度呢？20线程意味着绝大部分CPU几乎都要满线程了 这一定是最好的方案吗？

**Comment by NeymarL** [comment]
那要看你怎么定义最好了，我不敢保证这是最好的方案，不过也是我实验出来的结果。
