### ISSUE TITLE
ICGA Computer Olympiad 2018, Taipei

### ISSUE THREAD

**Issue by alreadydone** [NeymarL/ChineseChess-AlphaZero#15]
Just for your information
http://www.tcga.tw/icga-computer-olympiad-2018/en/#top
http://www.tcga.tw/icga-computer-olympiad-2018/en/#tsignup
http://icga.ntpu.edu.tw/icga2018/
https://zhuanlan.zhihu.com/p/36132041

**Comment by NeymarL** [comment]
Thank you for providing information!
