### ISSUE TITLE
UI上的两个小建议

### ISSUE THREAD

**Issue by qysnn** [NeymarL/ChineseChess-AlphaZero#16]
1. 当前走的子没有着重显示，建议像其他棋软一样，在当前走的子和其之前的位置的四角各加一个标志
2. 现在红黑方的位置是固定的，建议增加一个选项，使得人类方不论执红还是执黑都在棋盘的下方

**Comment by NeymarL** [comment]
UI我有点懒得改了，推荐使用UCI引擎吧
