### ISSUE TITLE
Dirichlet Noise

### ISSUE THREAD

**Issue by sharpobject** [NeymarL/ChineseChess-AlphaZero#17]
Hello,

Are you sure the Dirichlet noise at a root node should be regenerated each time the node is searched? It's not clear to me from the bit in the paper:
```
Additional exploration is achieved by adding Dirichlet noise 
to the prior probabilities in the root node s0, specifically 
P(s, a) = (1 − ε)p_a + εη_a, where η ∼ Dir(0.03) and ε = 0.25; 
this noise ensures that  all moves may be tried, but the
 search may still overrule bad moves
```
but it seems like this is something you can do just one time in the root node, then keep the same noise for all 50 or 100 or 1600 searches.

**Comment by NeymarL** [comment]
Yes, every time you select actions from the root node, a new Dirichlet noise will be generated and add to the prior probability.
