### ISSUE TITLE
About the MCTS parameters

### ISSUE THREAD

**Issue by JianqiaoAirport** [NeymarL/ChineseChess-AlphaZero#18]
Thanks for your excellent work!

I implemented an AlphaGomoku Zero a few months ago. The algorithm indeed works to some extend, but after trainning for about 1500 steps (each step has a mini-batch of 256), the agent seems to stop learning and just chooses almost the same action and makes the same mistake. 
I fund that in AlphaGo Zero's paper, the MCTS parameters such as "c_puct" is optimized by Gaussian process:

MCTS search parameters were selected by Gaussian process optimization, so as to optimize self­-play performance of AlphaGo Zero using a neural network trained in a preliminary run. 

I am not familiar with Gaussian process, in my implementation, the c_puct is a constant. I wonder how do you deal with the c_puct, and how gaussian process is applied to this scenario. Could you share your opinion?

**Comment by NeymarL** [comment]
In my opinion, the "c_puct" parameter maybe not the key reason to let your agent "stop learning". As far as I am concerned, the major reasons including
* Randomness is too little in self-play. You should tune temperature and Dirichlet noise to increase the diversity of self-play games.
* Simply the data is not enough. I mean the data may be too little for the agent to learn the pattern.

By the way, my "c_puct" parameter is also a constant and is referred from other projects. So I don't apply Gaussian process to it. Hope this will help you.

**Comment by JianqiaoAirport** [comment]
Thank you so much and I will try again
