### ISSUE TITLE
目前棋力如何呢

### ISSUE THREAD

**Issue by handsomeeeee** [NeymarL/ChineseChess-AlphaZero#2]
請問目前的棋力如何了呢 不知道你們有沒有聽說目前圍棋AI leelazero項目 是由一個老外寫的代碼 然後由廣大網友一起用家中電腦訓練的ai 目前已經劍指alphago以外的最強ai了! 建議你們也可以採用這種方式 在各大網站宣傳 支持!!

**Comment by NeymarL** [comment]
多谢支持。目前棋力还很弱，似乎还有些bug导致自我博弈不能越下越好，正在调试中。
