### ISSUE TITLE
For non developers it cant start the self play

### ISSUE THREAD

**Issue by aspoofer** [NeymarL/ChineseChess-AlphaZero#22]
[]
![python](https://user-images.githubusercontent.com/28191119/44627508-b9dd2580-a961-11e8-8eec-8519d2d4675a.png)

**Comment by aspoofer** [comment]
这个是GPU版本的

**Comment by emc2314** [comment]
正常, 你是英文系统, cmd 不支持显示中文. 这是提示你输入用户名....

**Comment by aspoofer** [comment]
能教我吗？ 我应该怎样做
![pthon2](https://user-images.githubusercontent.com/28191119/44628375-e3517d80-a970-11e8-8a80-427c93b8ed06.png)
无论我Y 还是 N 都会自动关闭

**Comment by aspoofer** [comment]
开到了 谢谢
