### ISSUE TITLE
请使用 统一码 Unicode 进行编程

### ISSUE THREAD

**Issue by S0ngSinGin** [NeymarL/ChineseChess-AlphaZero#23]
@NeyMarL 你好：
编写".exe"、储存".txt"等相关文件的时候，建议使用 统一码 "Unicode"。
这样“中国象棋零”在非中文操作系统之下运行，可以正常显示中文汉字菜单。
希望每个中国软件企业、程序人员都能留意到这个细节，让中文软件可以通行全球，同英文拉丁字母并驾齐驱！
详请参阅 微软文章 [支持统一码](https://msdn.microsoft.com/zh-cn/library/2dax2h36.aspx)、[字符集可迁移性](https://msdn.microsoft.com/zh-cn/library/zhkk3525.aspx)、百度百科 [Unicode](https://baike.baidu.com/item/Unicode/750500#9)词条，为国际市场编程！
（也请大家推广周知）
非Unicode程序 运行时须借助 "微软[AppLocale](https://zh.wikipedia.org/zh-cn/Microsoft_AppLocale)"(应用在地化)等 转码工具，且有漏洞不补，
甚而2016起，微软不再提供"AppLocale"，似有抑制中文扩散的意图。

**Comment by NeymarL** [comment]
You're right.😄
