### ISSUE TITLE
有没有javascript版本的？

### ISSUE THREAD

**Issue by leeseean** [NeymarL/ChineseChess-AlphaZero#24]
我想做个html5在线游戏，然后用你开发的阿发狗的AI，该怎么弄？谢谢

**Comment by NeymarL** [comment]
如果想做在线版的你需要一台拥有不错的GPU的Web服务器，然后使用JavaScript或其他编程语言通过调用外部程序的方式与引擎交互。

**Comment by leeseean** [comment]
怎么调用啊？

**Comment by NeymarL** [comment]
比如你可以使用Python写后端，然后提供借口给js。
