### ISSUE TITLE
关于google colaboratory，如何使用TPU来训练呢？

### ISSUE THREAD

**Issue by aspoofer** [NeymarL/ChineseChess-AlphaZero#26]
![image](https://user-images.githubusercontent.com/28191119/46901852-a5db8c00-ceed-11e8-9c4e-9ebd8d10e5b5.png)

**Comment by NeymarL** [comment]
TPU只能用来train，没法inference，所以无法跑谱

**Comment by aspoofer** [comment]
ok谢谢
