### ISSUE TITLE
【请教】请教实现细节

### ISSUE THREAD

**Issue by CharlesLiuyx** [NeymarL/ChineseChess-AlphaZero#29]
非常感谢作者优秀项目！

这边有几个实现细节请教作者（可以看源码，原谅我偷个懒）
（1）象棋的棋盘状态的编码方式（输入）
（2）输出的具体编码格式

再次感谢

**Comment by NeymarL** [comment]
1. 输入大小为14x10x9：10x9是象棋棋盘大小；14是棋子个数。所以输入就是每个棋子在棋盘中的位置
2. 输出就是一个2086维的Vector，因为每一步总共有2086种可能的走法。

**Comment by CharlesLiuyx** [comment]
2086种就是考虑象棋规则的走子空间Vector吧？

**Comment by NeymarL** [comment]
是的

**Comment by CharlesLiuyx** [comment]
数值直接就是对应的可能概率，和AlphaGo Zero一样，还有一个Value头的局面判断，就是最后的输出？感谢您的回复，询问是因为自己做了一个开源项目 [tensorspace.org](tensorspace.org)，想用您们的模型做个Example，引用项目的链接！感谢

**Comment by NeymarL** [comment]
是的。请随意使用，期待你们的成果。

**Comment by CharlesLiuyx** [comment]
感谢，之后具体问题就在这个Issue下面聊，或者唐突加个微信？Uranus_LYX

**Comment by Wenjiaw** [comment]
冒昧问一句。14x10x9 棋子的数量是14 ？ 但是共有16个棋子啊，那是哪两个没有用到那

**Comment by NeymarL** [comment]
车，马，炮，士，相，帅，卒
