### ISSUE TITLE
哥们，太多的人，就等你了，然后大家一起训练

### ISSUE THREAD

**Issue by 1715509415** [NeymarL/ChineseChess-AlphaZero#3]
哥们，太多的人，就等你了，然后大家一起训练，有没有这样的打算呀

**Comment by NeymarL** [comment]
话说怎么一起训练？

**Comment by 1715509415** [comment]
训练不是要棋谱吗，我们self好棋谱后传给你训练生成权重呀，然后我们又用新的权重再生成棋谱再传给你，再生成权重，这样，就比你一个人单机快得多了

**Comment by NeymarL** [comment]
目前有多少人呐，我有时间弄个Web Server试试

**Comment by 1715509415** [comment]
如果你弄成了，就去几个alphazero群，如围棋群，国际象棋群说已经开始跑中国象棋zero了，那肯定就会有人来跑棋谱的，因为这些群都有一群人说什么时候有中国象棋的zero，讨论的人特别多，都是希望能打到旋风和名手的人。http://lczero.org   ，https://github.com/glinscott/leela-chess 这是国际象棋的。如果你能搞成分布式运行，那就一百两百个权重就打败现在中国最厉害的中国象棋软件了

**Comment by NeymarL** [comment]
基本的分布式功能实现了，说明在这里：https://github.com/NeymarL/ChineseChess-AlphaZero/wiki/Getting-Started ，能不能给我几个群号，我去里面说说

**Comment by 1715509415** [comment]
把你的邮箱给我吧。

**Comment by 1715509415** [comment]
把你的邮箱给我吧。

**Comment by 1715509415** [comment]
你这里好像没有让那些不是程序员的人来运行的exe文件啊，人家只会运行windows的文件，可不会安装什么编译环境哦，一到还要安装别的什么的，人家可就直接溜了。要一步到位啊，如让人家一键self棋谱然后直接保存上传。然后得到权重model就可直接下棋了。可是你这里让那些没有安装编译环境的人是无法运行的吧。

**Comment by NeymarL** [comment]
也是，我看看能不能弄出个exe来

**Comment by 1715509415** [comment]
记得要说明，哪个是self棋谱保存上传，哪个是下棋程序，还有如何运用权重model。这三个最重要。

**Comment by houzhenggangGit** [comment]
正在学习你的代码，在做alphazero的毕业设计。这里可以贡献一个双路1080ti服务器

**Comment by houzhenggangGit** [comment]
我在训练你的项目还有另一个国际象棋项目发现gpu利用率都不高，看了看issues，应该是io限制了gpu的效率，目前你有办法解决吗？

**Comment by NeymarL** [comment]
我自己训练的时候GPU利用率挺高的，在99%左右。如果你有两个GPU，可以开两个self-play分别在两块GPU上跑；也有可能跟设置里的搜索进程数、线程数、和模拟次数有关。

**Comment by houzhenggangGit** [comment]
谢谢！回去试一试

**Comment by luogang105814** [comment]
Python不会弄啊，作者大大还是尽量做一个分布式训练客户端，对于我们这些非专业人士省时又省力，具体可参考leela chess。
https://github.com/glinscott/leela-chess/tree/v0.4

**Comment by NeymarL** [comment]
@luogang105814  已经在弄了，稍安勿躁:)

**Comment by luogang105814** [comment]
请问作者是按照中国规则做的还是亚洲规则？

**Comment by NeymarL** [comment]
@luogang105814 我不知道有什么区别，但应该是中国规则吧

**Comment by luogang105814** [comment]
作者大大，这是今天几个爱好者创建的一个群，希望您能来指导，欢迎加入象棋ZERO，群聊号码：706396552

**Comment by NeymarL** [comment]
@luogang105814 客气了，已申请入群
