### ISSUE TITLE
Google跑不到谱

### ISSUE THREAD

**Issue by aspoofer** [NeymarL/ChineseChess-AlphaZero#30]
![image](https://user-images.githubusercontent.com/28191119/48125330-653b1c80-e2b9-11e8-8196-1470117141b5.png)
cchess_alphazero.worker.self_play INFO # Exception Shape must be rank 1 but is rank 0 for 'input_batchnorm_4/cond/Reshape_4' (op: 'Reshape') with input shapes: [1,192,1,1], []., 重新加载权重
2018-11-07 10:16:32,709@cchess_alphazero.agent.model DEBUG # loading model from /content/ChineseChess-AlphaZero/data/model/model_192x10_config.json  不断跳出这种信息

**Comment by NeymarL** [comment]
在第一行加上`!pip install keras==2.0.9`

**Comment by aspoofer** [comment]
ok 能跑了
