### ISSUE TITLE
 APV-MCTS和Virtual Loss在哪里 

### ISSUE THREAD

**Issue by initial-h** [NeymarL/ChineseChess-AlphaZero#31]
RT。
想学习一下异步树搜索的写法，请问在哪个文件里呢？以及作者博客里说使用了多线程搜索，python的多线程貌似还是在单核上运行的，不知道是否有看到加速效果？

**Comment by NeymarL** [comment]
MCTS在`agent/player.py`（看了博客应该知道的）。
多线程是有加速效果的，因为单线程的话在等待神经网络返回结果的时候基本是闲着的，而多进程则可以利用等待时间继续下一次搜索（即使是运行在单核上的）。

**Comment by initial-h** [comment]
也就是说这个加速效果会被限制在一个CPU核里，没有利用多核的计算能力，这么理解对吗？

**Comment by NeymarL** [comment]
是的
