### ISSUE TITLE
Pingfang.ttc

### ISSUE THREAD

**Issue by Wenjiaw** [NeymarL/ChineseChess-AlphaZero#32]
你好，
我试图在你提供的网站上找一个PingFang.ttc文件，网站上面显示404 not found

Note: Before you start, you need to download/find a font file (.ttc) and rename it as PingFang.ttc, then put it into cchess_alphazero/play_games. I have removed the font file from this repo because it's too big, but you can download it from here.

请问有什么解决办法吗

**Comment by NeymarL** [comment]
现在应该可以了

**Comment by Wenjiaw** [comment]
非常感谢！另外一个问题是如果我想用 https://cczero.org/api/models 中的models，但是我只发现.h5文件，没有相对应的.json 文件，是否以为着.json 文件可以通用。

**Comment by NeymarL** [comment]
基本上是的
