### ISSUE TITLE
请问最新的模型是什么水平？

### ISSUE THREAD

**Issue by fancyerii** [NeymarL/ChineseChess-AlphaZero#35]
5000分大概什么水平？希望超越的旋风大概多少分？

**Comment by NeymarL** [comment]
就是差不多天天业9水平，不知道超越旋风要多少分

**Comment by fancyerii** [comment]
搜索了一下。根据 https://zhidao.baidu.com/question/1960918469615278380.html ，手机天天象棋棋力测评等级依次是：业余一级，业余两级，业余三级，业余四级，业余五级，业余六级，业余七级，业余八级，业余九级，业余大师，大师，国家大师，特级大师，共13级！
根据http://cyclone.xqbase.com/intro.htm#intro_2

棋手 | 等级分
-- | --
象棋巫师免费引擎 | 2000
象棋巫师超级引擎基础版 | 2500
象棋旋风三代基础版 | 2580
象棋旋风三代专业版 | 2640
象棋旋风三代旗舰版 | 2700
人类中国象棋冠军 | 2700
象棋旋风四代基础版 | 2700
象棋旋风四代专业版 | 2760
象棋旋风四代旗舰版 | 2820

http://www.xiangqiqipu.com/Category/View-15326.html ，我看人类最高的等级分也在2700-2800之间。因此象棋旋风能够达到或者稍微超过人类顶级选手。

我感觉天天业9大概是2200的等级分，不知道这个估计是否正确？

**Comment by NeymarL** [comment]
嗯，差不多吧

**Comment by fancyerii** [comment]
那感觉差距还是不小。
