### ISSUE TITLE
关于学习率和搜索效率的问题和建议

### ISSUE THREAD

**Issue by vigor95** [NeymarL/ChineseChess-AlphaZero#36]
（1）现在大概训练了三四百万局，请问学习率是如何调的呢？是通过观察棋力增长曲线（趋于平缓时lr除以10），还是有别的方法？

（2）关于搜索树，我看到repo里用到了多线程，不太好确定这样做的效率，我会去跑一遍试一下。
我注意到FaceBook的ELF OpenGo是这样做的：一块卡上跑32个进程（也就是同时跑32局），每个进程里的搜索树每次攒4个叶子节点（这4个叶子对应的局面等待神经网络的evaluation），32个进程的128个局面一起送到神经网络里，这样就形成了batchsize=128的效果。感觉这种做法相当高效。
是否可以考虑实现ELF的做法？毕竟AGZ系的算法，self-play运行效率太重要。。。

**Comment by NeymarL** [comment]
1. 一般是连续多次的fail会降一下lr
2. 我们的多线程实现也差不多，但没有强制batch size多大，可能是1～256之间的任意大小
