### ISSUE TITLE
something wrong with “play”

### ISSUE THREAD

**Issue by pythonberg1997** [NeymarL/ChineseChess-AlphaZero#37]
ValueError: Shape must be rank 1 but is rank 0 for 'input_batchnorm/cond/Reshape_4' (op: 'Reshape') with input shapes: [1,192,1,1], []

**Comment by pythonberg1997** [comment]
I run "python cchess_alphazero/run.py play" ,and it cannot work

**Comment by zeromovie** [comment]
are you prepare this for latest Computer Game Competition？

**Comment by DleanJeans** [comment]
Here's a [Google Colab notebook](https://colab.research.google.com/drive/1oMbTo_4OopgThPo4LpJSxBO3BLh1zfmt) showing this error.


What's the point of training if you can't even play with it?

**Comment by DleanJeans** [comment]
Dunno why but it works when you run on a CPU or TPU instance.

![image](https://user-images.githubusercontent.com/12462089/62830287-c0c67c00-bc36-11e9-800f-b943b459e7f9.png)

**Comment by Loverush** [comment]
> Dunno why but it works when you run on a CPU or TPU instance.
> 
> ![image](https://user-images.githubusercontent.com/12462089/62830287-c0c67c00-bc36-11e9-800f-b943b459e7f9.png)

**Comment by pythonberg1997** [comment]
> Dunno why but it works when you run on a CPU or TPU instance.
> 
> ![image](https://user-images.githubusercontent.com/12462089/62830287-c0c67c00-bc36-11e9-800f-b943b459e7f9.png)

OK, I'll try. Thank you very much!

**Comment by DleanJeans** [comment]
The network takes like 30 seconds to make a move. Probably much faster if it works on a GPU or a TPU.

**Comment by DleanJeans** [comment]
Found the fix!

Just reinstall Keras from its GitHub repo:
```
pip install --no-deps --force-reinstall git+https://github.com/keras-team/keras
```

Source: https://github.com/keras-team/keras/issues/10648.

**Comment by pythonberg1997** [comment]
> Found the fix!
> 
> Just reinstall Keras from its GitHub repo:
> 
> ```
> pip install --no-deps --force-reinstall git+https://github.com/keras-team/keras
> ```
> 
> Source: [keras-team/keras#10648](https://github.com/keras-team/keras/issues/10648).

Got it! Thank you again!
