### ISSUE TITLE
Where is the code base of distributed training server?

### ISSUE THREAD

**Issue by zhiyue** [NeymarL/ChineseChess-AlphaZero#4]
I want to look at the server code, I don't see the relevant code in the current repos

**Comment by NeymarL** [comment]
Well, I do not put the server-end code into github since there are some private pieces of information, e.g. database password, which are unsafe to open source. However, the back-end code is fairly easy based on PHP with CodeIgniter framework which you can find a lot of tutorials on the Internet.
