### ISSUE TITLE
数据训练相关问题

### ISSUE THREAD

**Issue by skarl-api** [NeymarL/ChineseChess-AlphaZero#68]
@NeymarL 您那目前有初始的训练数据吗？我发现目前的权重能力不是特别的强，所以我需要重新训练一下，另外我看您的网站好像目前无法访问了，也无法上传新的训练。我来训练吧，我手上目前有200多个GPU，做其他事情剩下来的，盼回复

**Comment by jjqtony** [comment]
盼回复，同样的问题！

**Comment by skarl-api** [comment]
@jjqtony optimize.py 训练初试数据你已找到了吗？

**Comment by skarl-api** [comment]
问题已自行解决

**Comment by sunchangshuan-git** [comment]
> 问题已自行解决

怎么解决的

**Comment by skarl-api** [comment]
> > 问题已自行解决
> 
> 怎么解决的

修改了一些代码就解决掉了；你这需要吗？我已经做成自动化下象棋工具了，类似鲨鱼象棋；
