### ISSUE TITLE
如下走棋是违规的

### ISSUE THREAD

**Issue by hilbertcao** [NeymarL/ChineseChess-AlphaZero#7]
http://alphazero.52coding.com.cn/api/view_pgn/play_20180424-165459.206508.json 28步违规了吧

**Comment by NeymarL** [comment]
不是强制应将的，他没有看到应将那一步，就走了别的

**Comment by hilbertcao** [comment]
@NeymarL 也就是通过训练来规避他去应将是吧，看多了他就不会应将?这样会不会浪费棋谱?不确定很少棋谱它能学会

**Comment by hilbertcao** [comment]
我看巫师的实现会规避让将帅在对方子力的吃的范围内，不知道这种判断会不会影响生成棋谱速度，但是可以减少一些明显无效的走法

**Comment by NeymarL** [comment]
以现在的水平是会应将的，只是训练时有噪音才会这样，评测或者和人下是会应将的
