### ISSUE TITLE
模型的输入层信息不够

### ISSUE THREAD

**Issue by archcra** [NeymarL/ChineseChess-AlphaZero#9]
目前为14 * 10 * 9，建议改为16 * 10 * 9：需要加入自然限招以及长杀等限招。希望能QQ沟通一下，我邮箱：archcra@qq.com

**Comment by NeymarL** [comment]
正在考虑加，你可以加群706396552

**Comment by archcra** [comment]
那个群不像是开发群。使用不正确的模型训练，会浪费资源。

**Comment by NeymarL** [comment]
浪费资源倒不至于，虽然神经网络的输入没有加，但是那些规则是都有的，最终下的棋是符合规则的；改了模型再拿之前的棋谱重新训练就行了
